config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'sso', to: 'home#sso'

  authenticate :user, ->(user) { user.administrator? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '(:locale)', locale: /ar|bg|cs|da|de|el|en|es|fi|fr|fr\-CA|he|hu|id|it|ja|ko|nb|nl|eo|pl|pt\-BR|ro|ru|sk|sr|sv|th|tr|uk|vi|zh\-CN|zh\-TW/ do
    get '/users', to: 'users#index', as: 'users'
    get '/users/webhook-info', to: 'users#webhook_info', as: 'user_webhook_info'
    post 'users/webhook-info', to: 'users#webhook_info'
    get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
    delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
    put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
    put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
    put '/users/update_password' => 'users#update_password', :as => 'user_update_password'
    get '/users/delete_info' => 'users#delete_info', :as => 'user_delete_info'
    post '/users/delete_start' => 'users#delete_start', :as => 'user_delete_start'
    get '/users/delete_confirm' => 'users#delete_confirm', :as => 'user_delete_confirm'
    post '/users/delete_complete' => 'users#delete_complete', :as => 'user_delete_complete'
    post '/dismiss_announcement/:key' => 'users#dismiss_announcement', as: 'dismiss_announcement'

    # disable destroying users
    devise_for :users, skip: :registrations, controllers: { sessions: 'sessions' }
    devise_scope :user do
      resource :registration,
               only: [:new, :create, :edit, :update],
               path: 'users',
               path_names: { new: 'sign_up' },
               controller: :registrations,
               as: :user_registration do
        get :cancel
      end
    end
    devise_scope :user do
      # a GET path for logging out for use with the forum
      get '/users/sign_out' => 'sessions#destroy'
      get '/auth/:provider/callback', to: 'sessions#omniauth_callback', as: 'omniauth_callback'
      # BrowserID POSTs
      post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
      get '/auth/failure', to: 'sessions#omniauth_failure'
      get '/auth/failure2', to: 'sessions#omniauth_failure'
      post '/users/send_confirmation_email' => 'users#send_confirmation_email'
    end

    root to: 'home#index'

    get 'scripts/sync_additional_info_form', to: 'scripts#sync_additional_info_form', as: 'script_sync_additional_info_form'
    resources :scripts, only: [:index, :show] do
      member do
        # Deprecated after https://github.com/JasonBarnabe/greasyfork/issues/76
        get 'code.meta.js', to: 'scripts#meta_js', locale: nil
        get 'code.user.js', to: 'scripts#user_js', locale: nil

        match 'code/:name.user.js', to: 'scripts#user_js', as: 'user_js', locale: nil, via: [:get, :options]
        match 'code/:name.user.css', to: 'scripts#user_css', as: 'user_css', locale: nil, via: [:get, :options]
        match 'code/:name.js', to: 'scripts#user_js', as: 'library_js', locale: nil, via: [:get, :options]
        match 'code/:name.meta.js', to: 'scripts#meta_js', as: 'meta_js', locale: nil, via: [:get, :options]
        match 'code/:name.meta.css', to: 'scripts#meta_css', as: 'meta_css', locale: nil, via: [:get, :options]

        get 'admin'
        get 'code(.:format)', to: 'scripts#show_code', as: 'show_code', constraints: { format: /.*/ }
        get 'derivatives'
        get 'similar-search', to: 'scripts#similar_search', as: 'similar_search'
        get 'diff', constraints: ->(req) { !req.params[:v1].blank? && !req.params[:v2].blank? }
        get 'feedback'
        get 'report'
        get 'stats'

        post 'install-ping', locale: nil

        get 'mark'
        post 'mark', to: 'scripts#do_mark', as: 'do_mark'

        get 'delete'
        post 'delete', to: 'scripts#do_delete', as: 'do_delete'
        post 'undelete', to: 'scripts#do_undelete', as: 'do_undelete'
        post 'request_permanent_deletion'
        post 'unrequest_permanent_deletion'
        post 'do_permanent_deletion', to: 'scripts#do_permanent_deletion', as: 'do_permanent_deletion'
        post 'reject_permanent_deletion', to: 'scripts#reject_permanent_deletion', as: 'reject_permanent_deletion'
        patch 'approve'

        patch 'sync_update'
        patch 'update_promoted'
        patch 'update_locale'
        post 'invite'
        get 'accept_invitation'
        post 'remove_author'
        post 'request_duplicate_check'
      end

      collection do
        get 'by-site(.:format)', action: 'by_site', as: 'site_list'
        # :site can contain a dot, make sure site doesn't eat format or vice versa
        get 'by-site/:site(.:format)', action: 'index', as: 'by_site', constraints: { site: /.*?/, format: /|html|atom|json|jsonp/ }
        get 'reported(.:format)', action: 'reported', as: 'reported'
        get 'reported_not_adult(.:format)', action: 'reported_not_adult', as: 'reported_not_adult'
        get 'libraries(.:format)', action: 'libraries', as: 'libraries'
        get 'search(.:format)', action: 'search', as: 'search'
        get 'minified(.:format)', action: 'minified', as: 'minified'
        get 'code-search(.:format)', action: 'code_search', as: 'code_search'
      end

      resources :script_versions, only: [:create, :new, :index], path: 'versions' do
        get 'delete(.:format)', to: 'script_versions#delete', as: 'delete'
        post 'delete(.:format)', to: 'script_versions#do_delete', as: 'do_delete'
      end

      resources :script_reports, path: 'reports', only: [:new, :create, :show, :index] do
        member do
          patch :rebut
          patch :resolve_delete
          patch :dismiss
        end
      end
    end
    resources :script_versions, only: [:create, :new]
    get 'script_versions/additional_info_form', to: 'script_versions#additional_info_form', as: 'script_version_additional_info_form'
    get 'script_versions/confirm_new_author', to: 'script_versions#confirm_new_author', as: 'script_version_confirm_new_author'
    resources :users, only: :show do
      post 'webhook'
      resources :script_sets, only: [:create, :new, :edit, :update, :destroy], path: 'sets'
      get 'ban', to: 'users#ban', as: 'ban'
      post 'ban', to: 'users#do_ban', as: 'do_ban'
    end
    post 'script_sets/add_to_set', to: 'script_sets#add_to_set', as: 'add_to_script_set'

    get 'import', to: 'import#index', as: 'import_start'
    get 'import/userscriptsorg', to: 'import#userscriptsorg', as: 'import_userscriptsorg'
    post 'import/verify', to: 'import#verify', as: 'import_verify'
    post 'import/add', to: 'import#add', as: 'import_add'
    get 'import/url', to: 'import#url', as: 'import_url'

    get 'help', to: 'help#index', as: 'help'
    get 'help/allowed-markup', to: 'help#allowed_markup', as: 'help_allowed_markup'
    get 'help/code-rules', to: 'help#code_rules', as: 'help_code_rules'
    get 'help/contact', to: 'help#contact', as: 'help_contact'
    get 'help/credits', to: 'help#credits', as: 'help_credits'
    get 'help/external-scripts', to: 'help#external_scripts', as: 'help_external_scripts'
    get 'help/installing-user-scripts', to: 'help#installing_user_scripts', as: 'help_installing_user_scripts'
    get 'help/installing-user-styles', to: 'help#installing_user_styles', as: 'help_installing_user_styles'
    get 'help/writing-user-scripts', to: 'help#writing_user_scripts', as: 'help_writing_user_scripts'
    get 'help/rewriting', to: 'help#rewriting', as: 'help_rewriting'
    get 'help/meta-keys', to: 'help#meta_keys', as: 'help_meta_keys'
    get 'help/privacy', to: 'help#privacy', as: 'help_privacy'
    get 'help/user-js-conversions', to: 'help#user_js_conversions', as: 'help_user_js_conversions'

    post 'preview-markup', to: 'home#preview_markup', as: 'preview_markup'
    get 'search', to: 'home#search'

    resources :moderator_actions, only: [:index]

    get 'opensearch.xml', to: 'opensearch#description', as: 'opensearch_description'

    resources :reports, only: [:new, :create, :index] do
      member do
        post :dismiss
        post :uphold
      end
    end

    namespace :admin do
      get '/' => 'home#index'
      resources :ads, only: [] do
        member do
          patch :approve
          patch :reject
        end
        collection do
          get :pending
        end
      end
      resource :analytics_stats, only: [:show, :update]
      resources :blocked_script_codes, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :blocked_script_texts, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :blocked_script_urls, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :redirect_service_domains, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :script_similarities, only: :index
      resources :spammy_email_domains, only: [:index, :new, :create, :edit, :update, :destroy]
    end

    match '*path', to: 'home#routing_error', via: [:get, :post]
  end

  match '*path', to: 'home#routing_error', via: [:get, :post]
end

app/views/script_versions/_additional_info.html.erb
<%
# Locals to pass in:
#  - la: localized_attribute for the additional info
#  - index: index of the additional info (to avoid duplicate names and IDs)
%>
<div class="form-control">
	<label>
		<%=t('activerecord.attributes.script.additional_info')%>
		<input type="hidden" name="script_version[additional_info][<%=index%>][attribute_default]" value="<%=la.attribute_default%>">
		<% if !la.attribute_default %>
			<select name="script_version[additional_info][<%=index%>][locale]">
				<option value="" <%if la.locale_id.nil?%>selected<%end%>><%=t('scripts.additional_info_locale_prompt')%></option>
				<% Locale.where(:ui_available => true).each do |locale| %>
					<option value="<%=locale.id%>" <%if la.locale_id == locale.id%>selected<%end%>><%=locale.display_text%></option>
				<% end %>
				<option disabled>---</option>
				<% Locale.all.each do |locale| %>
					<option value="<%=locale.id%>"<%if la.locale_id == locale.id%>selected<%end%>><%=locale.display_text%></option>
				<% end %>
			</select>
		<% end %>
	</label>
	<span class="label-note">
		<%=t('scripts.additional_info_note_html', {:allowed_elements_link => link_to( t('common.allowed_elements_link'), help_allowed_markup_path, {:target => 'markup_choice'})})%>
		<%=radio_button_tag("script_version[additional_info][#{index}][value_markup]", 'html', la.value_markup == 'html' || la.value_markup.nil?)%>HTML
		<%=radio_button_tag("script_version[additional_info][#{index}][value_markup]", 'markdown', la.value_markup == 'markdown')%><%=link_to 'Markdown', 'http://daringfireball.net/projects/markdown/basics', {:target => 'markup_choice'}%>
	</span><br>
	<div class="previewable" data-markup-option-name="script_version[additional_info][<%=index%>][value_markup]" data-preview-label="<%=t('common.preview_tab')%>" data-write-label="<%=t('common.write_tab')%>">
		<%=text_area_tag("script_version[additional_info][#{index}][attribute_value]", la.attribute_value, {:id => "script-version-additional-info-#{index}"})%>
	</div>
</div>

app/views/script_versions/_form.html.erb
<% content_for :head_bottom do %>
  <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <%= javascript_include_tag 'ace' %>
<% end %>

<p>
  <%=t('scripts.rules_summary_html', {:full_rules_link => link_to(t('scripts.rules_summary_link_to_full'), help_code_rules_path)})%>
</p>

<% # ignore userscripts.org sync
if !script_version.script.script_sync_type_id.nil? and script_version.script.script_sync_source_id != 2 %>
  <p>
    <%=t('scripts.syncing_notice_html', {
      :syncing_notice_sync_type => link_to(
        t(
          script_version.script.script_sync_type_id == 1 ? 'scripts.syncing_notice_sync_type_manual' : 'scripts.syncing_notice_sync_type_automatic',
          {:sync_identifier => script_version.script.sync_identifier}
        ),
        admin_script_path(script_version.script_id)
      )
    })%>
  </p>
<% end %>

<%=form_for(script_version.script.new_record? ? script_version : [script_version.script, script_version], {:html => {:enctype => 'multipart/form-data'}}) do |s| %>

  <% # remember previously chosen overrides
  [:version_check_override, :add_missing_version, :namespace_check_override, :add_missing_namespace, :minified_confirmation, :allow_code_previously_posted].each do |override|
    if script_version.send(override) %>
      <%=s.hidden_field(override)%>
    <% end
  end %>

  <%= hidden_field_tag(:language, script_version.script.language) if script_version.script.new_record? %>

  <% if !script_version.errors.empty? or !script_version.script.errors.empty? %>
    <div class="alert">
      <p><%=t('common.error_preamble')%></p>
      <ul class="errors">
        <% displayed_errors = []
        script_version.screenshots.each do |screenshot|
          screenshot.errors.each do |attr, msg|
            displayed_errors << attr.to_s.humanize + ' ' + msg
          end
        end
        script_version.errors.each do |attr, msg|
          # need custom handling for warnings
          next if msg.starts_with?('warning-') || attr.to_s.include?('screenshot')
          if attr == :base
            if msg == "appears to be an unauthorized copy" && script_version.unauthorized_original
              displayed_errors << it('scripts.error_unauthorized_copy',
                script: link_to(script_version.unauthorized_original.name(I18n.locale), script_path(script_version.unauthorized_original)),
                rules_link: help_code_rules_path,
                site_name: site_name,
              )
            else
              displayed_errors << msg
            end
          elsif msg.is_a?(String)
            displayed_errors << "#{attr.to_s.capitalize} #{msg}"
          else
            displayed_errors << script_version.errors.generate_message(attr, msg)
          end
        end
        script_version.script.errors.full_messages.each do |m|
          displayed_errors << m
        end
        displayed_errors.uniq.each do |err| %>
          <li><%=err%></li>
        <% end
        script_version.warnings.each do |w| %>
          <li><%
            case w
              when :version_not_incremented %>
                <%=t('scripts.warning_version_not_incremented_html')%><br>
                <label for="script_version_version_check_override"><%=t('scripts.override_warning_checkbox_label')%></label> <%=s.check_box(:version_check_override, {}, true, false)%>
              <% when :version_missing %>
                <%=t('scripts.warning_version_missing_html')%><br>
                <label for="script_version_add_missing_version"><%=t('scripts.warning_version_missing_generate_automatically_html')%></label> <%=s.check_box(:add_missing_version, {}, true, false)%>
              <% when :namespace_missing %>
                <%=t('scripts.warning_namespace_missing_html')%><br>
                <label for="script_version_add_missing_namespace"><%=t('scripts.warning_namespace_missing_generate_automatically_html')%></label> <%=s.check_box(:add_missing_namespace, {}, true, false)%>
              <% when :namespace_changed %>
                <%=t('scripts.warning_namespace_changed_html')%><br>
                <label for="script_version_namespace_check_override"><%=t('scripts.override_warning_checkbox_label')%></label> <%=s.check_box(:namespace_check_override, {}, true, false)%>
              <% when :potentially_minified %>
                <%=t('scripts.warning_potentially_minified_html', {:allowed_requires_link => link_to(t('scripts.warning_potentially_minified_allowed_requires_link'), help_external_scripts_path())})%><br>
                <label for="script_version_minified_confirmation"><%=t('scripts.override_warning_checkbox_label')%></label> <%=s.check_box(:minified_confirmation, {}, true, false)%>
              <% when :automatic_sensitive %>
                <%=t('scripts.warning_automatic_sensitive_html', {sensitive_domains: script_version.sensitive_domains.to_sentence})%><br>
                <label for="script_version_minified_confirmation"><%=t('scripts.override_warning_checkbox_label')%></label> <%=s.check_box(:sensitive_site_confirmation, {}, true, false)%>
              <% when :code_previously_posted %>
                <%= t('scripts.warning_code_previously_posted_html', { script_links: script_version.previously_posted_scripts.map { |s| link_to(s.name(I18n.locale), script_path(s)) }.to_sentence.html_safe}) %><br>
                <label for="script_version_allow_code_previously_posted"><%=t('scripts.override_warning_checkbox_label')%></label> <%=s.check_box(:allow_code_previously_posted, {}, true, false)%>
              <% else
                raise "Unknown warning #{w}"
            end %>
          </li><%
        end %>
      </ul>
    </div>
  <% end %>

  <% if @script.library? %>
    <div class="form-control">
      <label for="library-name"><%=t('activerecord.attributes.script.name')%></label><br>
      <input id="library-name" name="name" value="<%=@script.name%>" maxlength="100">
    </div>
    <div class="form-control">
      <label for="library-description"><%=t('activerecord.attributes.script.description')%></label><br>
      <input id="library-description" name="description" value="<%=@script.description%>" maxlength="500">
    </div>
  <% end %>
  <div class="form-control">
    <label for="script_version_code"><%=t('activerecord.attributes.script.code')%></label> <span class="label-note" style="display: none"><input type="checkbox" id="enable-source-editor-code" name="enable-source-editor-code" <%if params['enable-source-editor-code']%>checked<%end%> class="enable-source-editor" data-related-editor="script_version_code" data-editor-language="<%= script_version.css? ? 'css' : 'javascript' %>"><label for="enable-source-editor-code" class="checkbox-label"><%=t('scripts.enable_source_code_editor_label')%></label></span><br>
    <%=s.text_area(:code)%>
    <div><%=t('scripts.upload_label')%> <input type="file" name="code_upload" id="code-upload" accept="text/javascript,application/javascript"></div>
  </div>
  <% if !script_version.script.new_record? %>
    <div class="form-control">
      <label for="changelog"><%=t('activerecord.attributes.script.changelog')%></label> <span class="label-note"><%=t('scripts.changelog_note')%></span><br>
      <%=s.text_field(:changelog, :maxlength => 500, :size => nil)%>
    </div>
  <% end %>
  <div class="form-control radio-group">
    <label><%=t('activerecord.attributes.script.type')%></label><br>
    <% ScriptType.for_language(script_version.script.language).each do |st| %>
      <%=radio_button('script', 'script_type_id', st.id)%> <label class="radio-label" for="script_script_type_id_<%=st.id%>"><%=t("scripts.type_#{st.id}_html", site_name: site_name)%></label><br>
    <% end %>
  </div>
  <% if !script_version.script.sensitive || script_version.script.adult_content_self_report %>
    <div class="form-control radio-group">
      <label><%=t('scripts.adult_content')%></label><br>
      <%=t('scripts.adult_content_self_report_explanation', site_name: site_name)%><br>
      <%= check_box('script', :adult_content_self_report) %>
      <label for="script_adult_content_self_report" class="radio-label"><%=t('scripts.adult_content_self_report')%></label>
    </div>
  <% else %>
    <div class="form-control radio-group">
      <label><%=t('scripts.adult_content')%></label><br>
      <% if @script.for_sensitive_site? %>
        <%=t('scripts.not_adult_content_self_report_explanation_automatic', site_name: site_name, domain_list: @script.matching_sensitive_sites.pluck(:domain).to_sentence)%><br>
      <% else %>
        <%=t('scripts.not_adult_content_self_report_explanation', site_name: site_name)%><br>
        <%= check_box('script', :not_adult_content_self_report, checked: @script.not_adult_content_self_report_date.present?) %>
        <label for="script_not_adult_content_self_report_date" class="radio-label"><%=t('scripts.not_adult_content_self_report_html')%></label>
      <% end %>
    </div>
  <% end %>

  <% if @script.css? %>
    <div class="form-control radio-group">
      <label><%=t('scripts.not_js_convertible_override_header')%></label><br>
      <%= it('scripts.not_js_convertible_override_explanation', site_name: site_name, help_link: help_user_js_conversions_path)%><br>
      <%= s.check_box :not_js_convertible_override %>
      <%= s.label :not_js_convertible_override, t('scripts.not_js_convertible_override_label_html'), class: 'radio-label' %>
    </div>
  <% end %>

  <% if @script.new_record? %>
    <div class="form-control radio-group">
      <label><%=t('activerecord.attributes.script.locale')%></label> <span class="label-note"><%=t('scripts.locale_explanation_html')%></span><br>
      <%= render partial: 'scripts/default_locale_selector', locals: {script: @script} %>
    </div>
  <% end %>

  <% # default first
  script_version.localized_attributes_for('additional_info').sort{|a,b|
    next -1 if a.attribute_default && !b.attribute_default
    next 1 if !a.attribute_default && b.attribute_default
    next 0
  }.each_with_index do |la, index| %>
    <%=render :partial => 'additional_info', :locals => {:la => la, :index => index}%>
  <% end %>

  <div class="form-control">
    <button id="add-additional-info" name="add-additional-info" value="1" type="submit"><%=t('scripts.additional_info_add_localized')%></button>
  </div>

  <div class="form-control screenshots-controls">
    <label><%=t('activerecord.attributes.script.screenshots')%></label> <span class="label-note"><%=t('scripts.screenshots_explanation', {:size => number_to_human_size(Rails.configuration.screenshot_max_size), :number => Rails.configuration.screenshot_max_count})%></span><br>
    <% @current_screenshots.each_with_index do |screenshot, i| %>
      <div class="screenshot-control">
        <a href="<%=screenshot.screenshot.url%>" data-jslghtbx="<%=screenshot.screenshot.url%>" data-jslghtbx-group="screenshots"><%= image_tag screenshot.screenshot.url(:thumb) %></a>
        <input maxlength="500" size="50" id="edit-screenshot-caption-<%=i%>" class="edit-screenshot-captions" name="edit-screenshot-captions[]" placeholder="<%=t('activerecord.attributes.script.screenshot_caption')%>" value="<%=screenshot.caption%>"><br>
        <input id="remove-screenshot-<%=screenshot.id%>" name="remove-screenshot-<%=screenshot.id%>" type="checkbox"><label class="checkbox-label" for="remove-screenshot-<%=screenshot.id%>"><%=t('scripts.screenshots_remove')%></label>
      </div>
    <% end %>
    <% 5.times do |i| %>
      <div class="add-screenshot-control">
        <label class="radio-label" for="add-screenshot-<%=i%>"><%=t('scripts.screenshots_add')%></label> <input type="file" id="add-screenshot-<%=i%>" class="add-screenshots" name="screenshots[]"> <input maxlength="500" size="50" id="add-screenshot-caption-<%=i%>" class="add-screenshot-captions" name="screenshot-captions[]" placeholder="<%=t('activerecord.attributes.script.screenshot_caption')%>"><br>
      </div>
    <% end %>
  </div>

  <%= flash[:recaptcha_error] %>

  <p>
    <%= invisible_recaptcha_tags callback: 'submitInvisibleRecaptchaFormScriptVersion', text: script_version.script.new_record? ? t('scripts.post_new_script') : t('scripts.post_updated_script') %>
  </p>
<% end %>

app/views/script_versions/delete.html.erb
<%- title "Delete v#{@script_version.version} of #{@script_version.script.name}" %>

<%=form_tag(script_script_version_do_delete_path) do |f|%>

	<% if !@script_version.errors.empty? %>
		<div class="alert">
			<p><%=t('common.error_preamble')%></p>
			<ul class="errors">
				<% @script_version.errors.full_messages.each do |e| %>
					<li><%=e%></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>You're about to permanently delete version <b><%=@script_version.version%></b> of <b><%=@script_version.script.name%></b>.</p>

	<p>
		<label for="reason">Why are you deleting this? (Don't be specific if it's a sensitive reason, like that version had a password in it.)</label><br>
		<textarea id="reason" name="reason" rows="5" cols="100" maxlength="500" required></textarea>
	</p>
	<input type="submit" value="Delete">
<% end %>

app/views/script_versions/disposable_email.html.erb
<p>
  <%= t('scripts.no_disposable_email') %>
</p>

app/views/script_versions/index.html.erb
<%- title t('scripts.history_title', :script_name => @script.name(request_locale)) %>
<%- description 'Version history for ' + @script.name(request_locale) %>

<% if @show_ad %>
  <!-- BEGIN COPY CODEFUND EMBED -->
  <div id="codefund"></div>
  <script
    src="https://app.codefund.io/properties/619/funder.js"
    async="async"></script>
  <!-- END COPY CODEFUND EMBED -->
<% end %>

<%
show_diff = @script.script_versions.length > 1
show_all_versions = !params[:show_all_versions].nil?
visible_version_index = 0
svs = @script.script_versions.reverse
if show_diff
	if !show_all_versions %>
		<p><%=t('scripts.history_only_code_changes_info')%> <%=link_to t('scripts.history_all_changes_link'), :show_all_versions => 1%></p>
	<% else %>
		<p><%=t('scripts.history_all_changes_info')%> <%=link_to t('scripts.history_only_code_changes_link'), :show_all_versions => nil%></p>
	<% end
end %>
<form action="<%=diff_script_path(params[:script_id])%>">
	<% if show_diff %>
		<%= submit_tag t('scripts.diff_button'), :name => nil%>
	<% end %>
	<ul class="history_versions">
		<% svs.each_with_index do |sv, i|
			show_version = show_all_versions || ((i + 1 >= svs.length) || sv.rewritten_script_code_id != svs[i + 1].rewritten_script_code_id)
			if show_version %>
				<li>
					<% if show_diff %>
						<input required type="radio" name="v1" value="<%=sv.id%>"<% if visible_version_index == 0%> checked<%end%>>
						<input required type="radio" name="v2" value="<%=sv.id%>"<% if visible_version_index == 1%> checked<%end%>>
					<% end
					visible_version_index += 1 %>
					<%=link_to 'v' + sv.version, script_path(sv.script, :version => sv.id), {:rel => :nofollow}%>
					<% if !current_user.nil? && current_user.moderator? %>
						<%=link_to 'Delete', script_script_version_delete_path(script_id: sv.script.id, script_version_id: sv.id) %>
					<% end %>
					<%=markup_date(sv.created_at)%>
					<% if !sv.changelog.nil? and !sv.changelog.empty? %>
						- <%=format_user_text(sv.changelog, sv.changelog_markup)%>
					<% end %>
				</li>
			<% end
		end %>
	</ul>
	<% if show_diff %>
		<%= submit_tag t('scripts.diff_button'), :name => nil%>
	<% end %>
</form>

app/views/script_versions/must_confirm.html.erb
<p>
  <%= t('scripts.must_confirm_email') %>
  <%= form_tag(controller: 'users', action: 'send_confirmation_email', method: :post) do %>
    <input type="submit" value="<%= t('scripts.must_confirm_email_button', email: current_user.email) %>">
  <% end %>
</p>

app/views/script_versions/new.html.erb
<% if @script.nil? or @script.new_record?
	title "Post new script" 
else
	title "Post new version of #{@script.name}" 
end %>

<%= render :partial => 'script_versions/form', :locals => {:script_version => @script_version} %>

app/views/script_versions/new_script_notice.html.erb
<h3><%= t('scripts.new_script_notice.title') %></h3>

<p>
  <%= link_to t('scripts.new_script_notice.install_link_html'), help_installing_user_scripts_path %>
</p>

<p>
  <%= link_to t('scripts.new_script_notice.share_link_html'), script_version_confirm_new_author_path(language: params[:language]) %>
</p>