config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'sso', to: 'home#sso'

  authenticate :user, ->(user) { user.administrator? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '(:locale)', locale: /ar|bg|cs|da|de|el|en|es|fi|fr|fr\-CA|he|hu|id|it|ja|ko|nb|nl|eo|pl|pt\-BR|ro|ru|sk|sr|sv|th|tr|uk|vi|zh\-CN|zh\-TW/ do
    get '/users', to: 'users#index', as: 'users'
    get '/users/webhook-info', to: 'users#webhook_info', as: 'user_webhook_info'
    post 'users/webhook-info', to: 'users#webhook_info'
    get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
    delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
    put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
    put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
    put '/users/update_password' => 'users#update_password', :as => 'user_update_password'
    get '/users/delete_info' => 'users#delete_info', :as => 'user_delete_info'
    post '/users/delete_start' => 'users#delete_start', :as => 'user_delete_start'
    get '/users/delete_confirm' => 'users#delete_confirm', :as => 'user_delete_confirm'
    post '/users/delete_complete' => 'users#delete_complete', :as => 'user_delete_complete'
    post '/dismiss_announcement/:key' => 'users#dismiss_announcement', as: 'dismiss_announcement'

    # disable destroying users
    devise_for :users, skip: :registrations, controllers: { sessions: 'sessions' }
    devise_scope :user do
      resource :registration,
               only: [:new, :create, :edit, :update],
               path: 'users',
               path_names: { new: 'sign_up' },
               controller: :registrations,
               as: :user_registration do
        get :cancel
      end
    end
    devise_scope :user do
      # a GET path for logging out for use with the forum
      get '/users/sign_out' => 'sessions#destroy'
      get '/auth/:provider/callback', to: 'sessions#omniauth_callback', as: 'omniauth_callback'
      # BrowserID POSTs
      post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
      get '/auth/failure', to: 'sessions#omniauth_failure'
      get '/auth/failure2', to: 'sessions#omniauth_failure'
      post '/users/send_confirmation_email' => 'users#send_confirmation_email'
    end

    root to: 'home#index'

    get 'scripts/sync_additional_info_form', to: 'scripts#sync_additional_info_form', as: 'script_sync_additional_info_form'
    resources :scripts, only: [:index, :show] do
      member do
        # Deprecated after https://github.com/JasonBarnabe/greasyfork/issues/76
        get 'code.meta.js', to: 'scripts#meta_js', locale: nil
        get 'code.user.js', to: 'scripts#user_js', locale: nil

        match 'code/:name.user.js', to: 'scripts#user_js', as: 'user_js', locale: nil, via: [:get, :options]
        match 'code/:name.user.css', to: 'scripts#user_css', as: 'user_css', locale: nil, via: [:get, :options]
        match 'code/:name.js', to: 'scripts#user_js', as: 'library_js', locale: nil, via: [:get, :options]
        match 'code/:name.meta.js', to: 'scripts#meta_js', as: 'meta_js', locale: nil, via: [:get, :options]
        match 'code/:name.meta.css', to: 'scripts#meta_css', as: 'meta_css', locale: nil, via: [:get, :options]

        get 'admin'
        get 'code(.:format)', to: 'scripts#show_code', as: 'show_code', constraints: { format: /.*/ }
        get 'derivatives'
        get 'similar-search', to: 'scripts#similar_search', as: 'similar_search'
        get 'diff', constraints: ->(req) { !req.params[:v1].blank? && !req.params[:v2].blank? }
        get 'feedback'
        get 'report'
        get 'stats'

        post 'install-ping', locale: nil

        get 'mark'
        post 'mark', to: 'scripts#do_mark', as: 'do_mark'

        get 'delete'
        post 'delete', to: 'scripts#do_delete', as: 'do_delete'
        post 'undelete', to: 'scripts#do_undelete', as: 'do_undelete'
        post 'request_permanent_deletion'
        post 'unrequest_permanent_deletion'
        post 'do_permanent_deletion', to: 'scripts#do_permanent_deletion', as: 'do_permanent_deletion'
        post 'reject_permanent_deletion', to: 'scripts#reject_permanent_deletion', as: 'reject_permanent_deletion'
        patch 'approve'

        patch 'sync_update'
        patch 'update_promoted'
        patch 'update_locale'
        post 'invite'
        get 'accept_invitation'
        post 'remove_author'
        post 'request_duplicate_check'
      end

      collection do
        get 'by-site(.:format)', action: 'by_site', as: 'site_list'
        # :site can contain a dot, make sure site doesn't eat format or vice versa
        get 'by-site/:site(.:format)', action: 'index', as: 'by_site', constraints: { site: /.*?/, format: /|html|atom|json|jsonp/ }
        get 'reported(.:format)', action: 'reported', as: 'reported'
        get 'reported_not_adult(.:format)', action: 'reported_not_adult', as: 'reported_not_adult'
        get 'libraries(.:format)', action: 'libraries', as: 'libraries'
        get 'search(.:format)', action: 'search', as: 'search'
        get 'minified(.:format)', action: 'minified', as: 'minified'
        get 'code-search(.:format)', action: 'code_search', as: 'code_search'
      end

      resources :script_versions, only: [:create, :new, :index], path: 'versions' do
        get 'delete(.:format)', to: 'script_versions#delete', as: 'delete'
        post 'delete(.:format)', to: 'script_versions#do_delete', as: 'do_delete'
      end

      resources :script_reports, path: 'reports', only: [:new, :create, :show, :index] do
        member do
          patch :rebut
          patch :resolve_delete
          patch :dismiss
        end
      end
    end
    resources :script_versions, only: [:create, :new]
    get 'script_versions/additional_info_form', to: 'script_versions#additional_info_form', as: 'script_version_additional_info_form'
    get 'script_versions/confirm_new_author', to: 'script_versions#confirm_new_author', as: 'script_version_confirm_new_author'
    resources :users, only: :show do
      post 'webhook'
      resources :script_sets, only: [:create, :new, :edit, :update, :destroy], path: 'sets'
      get 'ban', to: 'users#ban', as: 'ban'
      post 'ban', to: 'users#do_ban', as: 'do_ban'
    end
    post 'script_sets/add_to_set', to: 'script_sets#add_to_set', as: 'add_to_script_set'

    get 'import', to: 'import#index', as: 'import_start'
    get 'import/userscriptsorg', to: 'import#userscriptsorg', as: 'import_userscriptsorg'
    post 'import/verify', to: 'import#verify', as: 'import_verify'
    post 'import/add', to: 'import#add', as: 'import_add'
    get 'import/url', to: 'import#url', as: 'import_url'

    get 'help', to: 'help#index', as: 'help'
    get 'help/allowed-markup', to: 'help#allowed_markup', as: 'help_allowed_markup'
    get 'help/code-rules', to: 'help#code_rules', as: 'help_code_rules'
    get 'help/contact', to: 'help#contact', as: 'help_contact'
    get 'help/credits', to: 'help#credits', as: 'help_credits'
    get 'help/external-scripts', to: 'help#external_scripts', as: 'help_external_scripts'
    get 'help/installing-user-scripts', to: 'help#installing_user_scripts', as: 'help_installing_user_scripts'
    get 'help/installing-user-styles', to: 'help#installing_user_styles', as: 'help_installing_user_styles'
    get 'help/writing-user-scripts', to: 'help#writing_user_scripts', as: 'help_writing_user_scripts'
    get 'help/rewriting', to: 'help#rewriting', as: 'help_rewriting'
    get 'help/meta-keys', to: 'help#meta_keys', as: 'help_meta_keys'
    get 'help/privacy', to: 'help#privacy', as: 'help_privacy'
    get 'help/user-js-conversions', to: 'help#user_js_conversions', as: 'help_user_js_conversions'

    post 'preview-markup', to: 'home#preview_markup', as: 'preview_markup'
    get 'search', to: 'home#search'

    resources :moderator_actions, only: [:index]

    get 'opensearch.xml', to: 'opensearch#description', as: 'opensearch_description'

    resources :reports, only: [:new, :create, :index] do
      member do
        post :dismiss
        post :uphold
      end
    end

    namespace :admin do
      get '/' => 'home#index'
      resources :ads, only: [] do
        member do
          patch :approve
          patch :reject
        end
        collection do
          get :pending
        end
      end
      resource :analytics_stats, only: [:show, :update]
      resources :blocked_script_codes, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :blocked_script_texts, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :blocked_script_urls, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :redirect_service_domains, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :script_similarities, only: :index
      resources :spammy_email_domains, only: [:index, :new, :create, :edit, :update, :destroy]
    end

    match '*path', to: 'home#routing_error', via: [:get, :post]
  end

  match '*path', to: 'home#routing_error', via: [:get, :post]
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/script_type.rb
class ScriptType < ApplicationRecord
  PUBLIC_TYPE_ID = 1
  UNLISTED_TYPE_ID = 2
  LIBRARY_TYPE_ID = 3

  scope :for_language, ->(lang) { lang.to_s == 'css' ? where.not(id: LIBRARY_TYPE_ID) : all }
end

app/helpers/scripts_helper.rb
require 'memoist'

module ScriptsHelper
  extend Memoist

  def script_list_link(label, sort: nil, site: nil, set: nil, default_sort: nil, language: nil, filter_locale: nil)
    is_link = true
    is_minified = action_name == 'minified'
    is_code_search = action_name == 'code_search'
    is_libraries = action_name == 'libraries'
    # sets can have a different default
    sort_param_to_use = (sort == default_sort) ? nil : sort
    if sort == params[:sort] && site == params[:site] && set == params[:set] && language == params[:language]
      l = label
      is_link = false
    elsif is_libraries
      l = link_to label, libraries_scripts_path(sort: sort_param_to_use, q: params[:q], set: set)
    elsif is_minified
      l = link_to label, minified_scripts_path(sort: sort_param_to_use)
    elsif is_code_search
      l = link_to label, code_search_scripts_path(sort: sort_param_to_use, c: params[:c])
    elsif site.nil?
      l = link_to label, { sort: sort_param_to_use, site: nil, set: set, q: params[:q], language: language, filter_locale: filter_locale }
    elsif params[:controller] == 'users'
      l = link_to label, { sort: sort_param_to_use, site: site, set: set, language: language, filter_locale: filter_locale }
    else
      l = link_to label, by_site_scripts_path(sort: sort_param_to_use, site: site, set: set, q: params[:q], language: language, filter_locale: filter_locale)
    end
    return ("<li class=\"list-option#{is_link ? '' : ' list-current'}\">" + l + '</li>').html_safe
  end

  def script_applies_to_list_contents(script, by_sites)
    sats_with_domains, sats_without_domains = script.script_applies_tos.includes(:site_application).partition(&:domain)
    return (
    sats_with_domains.map do |sat|
      content_for_script_applies_to_that_has_domain(sat, count_of_other_scripts_with_sat(sat, script, by_sites))
    end +
    sats_without_domains.map { |sat| content_tag(:code, sat.text) }
  )
  end

  def license_display(script)
    return link_to(script.license.code, script.license.url, title: script.license.name) if script.license&.url
    return script.license.code if script.license
    return "<i>#{I18n.t('scripts.no_license')}</i>".html_safe if script.license_text.nil?

    return script.license_text
  end

  def promoted_script
    return nil if sleazy?
    return nil if @script&.sensitive
    return nil if current_user && !current_user.show_ads
    return @script.promoted_script if @script&.promoted_script
    return nil unless Random.rand(Rails.application.config.promoted_script_divisor) == 0

    return Script.where(promoted: true).sample
  end
  memoize :promoted_script

  private

  def content_for_script_applies_to_that_has_domain(sat, count_of_other_scripts)
    if !sat.site_application.blocked && count_of_other_scripts > 0
      title = t('scripts.applies_to_link_title', { count: count_of_other_scripts, site: sat.text })
      return link_to(sat.text, by_site_scripts_path(site: sat.text), { title: title })
    end
    return sat.text
  end

  def count_of_other_scripts_with_sat(script_applies_to, script, by_sites)
    return 0 if by_sites[script_applies_to.text].nil?

    # take this one out of the count if it's a listable
    return (by_sites[script_applies_to.text][:scripts] - (script.listable? ? 1 : 0))
  end
end

app/views/scripts/_ratings.html.erb
<span class="good-rating-count" title="<%=t('scripts.good_rating_explanation')%>"><%=script.good_ratings%></span>
<span class="ok-rating-count" title="<%=t('scripts.ok_rating_explanation')%>"><%=script.ok_ratings%></span>
<span class="bad-rating-count" title="<%=t('scripts.bad_rating_explanation')%>"><%=script.bad_ratings%></span>

app/views/scripts/_script.html.erb
<%
show_author_details = defined?(show_author_details) && show_author_details
show_report_thread = defined?(show_report_thread) && show_report_thread
%>
<li data-script-id="<%=script.id%>" data-script-name="<%=script.name(request_locale)%>" data-script-authors="<%= script.users.map { |u| [u.id, u.name] }.to_h.to_json %>" data-script-daily-installs="<%=script.daily_installs%>" data-script-total-installs="<%=script.total_installs%>" data-script-rating-score="<%=script.fan_score%>" data-script-created-date="<%=script.created_at.strftime('%Y-%m-%d')%>" data-script-updated-date="<%=script.code_updated_at.strftime('%Y-%m-%d')%>" data-script-type="<%=script.script_type.short_name%>" data-script-version="<%=script.version%>" data-sensitive="<%=script.sensitive%>" data-script-language="<%= script.language %>" data-css-available-as-js="<%= script.css_convertible_to_js %>">
  <article>
    <h2>
      <%=link_to script.name(request_locale), script_path(script)%>
      <% if show_author_details && script.users.include?(current_user) && script.sensitive %>
        <span class="script-type"><%=t('scripts.adult_marker')%></span>
      <% end %>
      <% case script.script_type_id
        when 2 %>
          <span class="script-type"><%=t('scripts.unlisted_marker')%></span>
        <% when 3 %>
          <span class="script-type"><%=t('scripts.library_marker')%></span>
      <% end %>
      <% if script.deleted? %>
        <span class="script-type"><%=t('scripts.deleted_marker')%></span>
      <% end %>
      <% if script.locked %>
        <span class="script-type"><%=t('scripts.locked_marker')%></span>
      <% end %>
      <span class="name-description-separator">
        -
      </span>
      <span class="description">
        <%=script.description(I18n.locale)%>
      </span>
    </h2>
    <dl class="inline-script-stats">
      <dt class="script-list-author"><span><%=t('scripts.author_name')%></span></dt>
      <dd class="script-list-author"><span><%= script.users.map { |u| link_to(u.name, u) }.to_sentence.html_safe %></span></dd>
      <% if !script.library? %>
        <dt class="script-list-daily-installs"><span><%=t('scripts.daily_installs')%></span></dt>
        <dd class="script-list-daily-installs"><span><%=number_with_delimiter(script.daily_installs)%></span></dd>
        <dt class="script-list-total-installs"><span><%=t('scripts.total_installs')%></span></dt>
        <dd class="script-list-total-installs"><span><%=number_with_delimiter(script.total_installs)%></span></dd>
        <dt class="script-list-ratings"><span><%=t('scripts.ratings')%></span></dt>
        <dd class="script-list-ratings" data-rating-score="<%=script.fan_score%>"><span><%=render :partial => 'scripts/ratings', :locals => {:script => script}%></span></dd>
      <% end %>
      <dt class="script-list-created-date"><span><%=t('scripts.created_date')%></span></dt>
      <dd class="script-list-created-date"><span><%=markup_date(script.created_at)%></span></dd>
      <dt class="script-list-updated-date"><span><%=t('scripts.updated_date')%></span></dt>
      <dd class="script-list-updated-date"><span><%=markup_date(script.code_updated_at)%></span></dd>
    </dl>
    <% if show_report_thread && script.script_reports.unresolved.any? %>
      <ul>
        <% script.script_reports.unresolved.each do |report| %>
          <li>
            <%= link_to script_script_report_path(report.script, report) do %>
              <% unless report.actionable? %>
                <b>(Waiting for response)</b>
              <% end %>
              <%= l report.created_at.to_date %> -
              <% case report.report_type
              when ScriptReport::TYPE_UNAUTHORIZED_CODE %>
                Unauthorized copy:
              <% when ScriptReport::TYPE_MALWARE %>
                Malware:
              <% when ScriptReport::TYPE_SPAM %>
                Spam:
              <% when ScriptReport::TYPE_OTHER %>
                Other report:
              <% end %>
              <i>
                "<%= truncate(report.details, length: 100) %>"
              </i>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </article>
</li>

app/views/scripts/_set_locale.html.erb
<section class="multiform-page">
  <h3><%= t('scripts.admin.locale_heading') %></h3>

  <%=form_for(@script, :url => update_locale_script_path) do |s|%>
    <p><%= t('scripts.admin.locale_example_html', text: @script.full_text.truncate(100)) %></p>
    <p><%= it('scripts.admin.locale_multiple_note', meta_keys_link: help_meta_keys_path(anchor: 'meta-name-localized')) %></p>
    <%= render partial: 'default_locale_selector', locals: {script: @script} %>
    <input type="submit" value="<%= t('scripts.admin.update_locale') %>">
  <% end %>
</section>

app/views/scripts/delete.html.erb
<%- title "Delete #{@script.name}" %>

<% moderator_view = current_user.moderator? && !@script.user_ids.include?(current_user.id) %>

<% if @script.deleted? %>

  <% if @script.locked? && !moderator_view %>
    <p><%= t('scripts.deleted_undelete_notice_html', delete_reason: @script.delete_reason) %></p>
  <% else %>
    <%=form_tag(do_undelete_script_path) do |f|%>
      <% if moderator_view %>
        <p>
          <label for="reason">Why are you undeleting this?</label><br>
          <textarea id="reason" name="reason" rows="5" cols="100" maxlength="500" required></textarea>
        </p>
        <% users_to_unban = @script.users.select(&:banned) %>
        <% if users_to_unban.any? %>
          <p>
            <label for="unbanned">Unban <%= users_to_unban.map { |u| link_to(u.name, u) }.to_sentence.html_safe %>?</label> <input type="checkbox" id="unbanned" name="unbanned" value="1">
          </p>
        <% end %>
      <% end %>
      <input type="submit" value="Undelete">
    <% end %>
  <% end %>

  <% if !moderator_view %>
    <%= render partial: 'permanently_delete', locals: {script: @script} %>
  <% end %>

<% else %>

  <%=form_tag(do_delete_script_path) do |f|%>

    <% if !@script.errors.empty? %>
      <div class="alert">
        <p><%=t('common.error_preamble')%></p>
        <ul class="errors">
          <% @script.errors.full_messages.each do |e| %>
            <li><%=e%></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p><%=t('scripts.delete_explanation')%></p>

    <p>
    <%=t('scripts.delete_update_behaviour')%><br>
      <% ScriptDeleteType.all.each do |sdt|
        if params[:script_delete_type_id].nil?
          selected = sdt.id == 2 && moderator_view
        else
          selected = params[:script_delete_type_id] == sdt.id.to_s
        end %>
        <input type="radio" required id="script_delete_type_id_<%=sdt.id%>" name="script_delete_type_id" value="<%=sdt.id%>" <%if selected%>checked<%end%>> <label for="script_delete_type_id_<%=sdt.id%>"><%=t("scripts.delete_update_behaviour_#{sdt.id}")%></label><br>
      <% end %>
    </p>
    <p>
      <label for="replaced_by_script_id"><%=t('scripts.replacement_script_explanation')%></label>
      <input id="replaced_by_script_id" name="replaced_by_script_id" value="<%=params[:replaced_by_script_id] || @script.replaced_by_script_id%>">
    </p>
    <% if moderator_view %>
      <p>
        <label for="reason">Why are you deleting this?</label><br>
        <textarea id="reason" name="reason" rows="5" cols="100" maxlength="500" required></textarea>
      </p>
      <p>
        <label for="locked">Lock the script to prevent undelete by the <%= 'author'.pluralize(@script.users.count) %>?</label> <input type="checkbox" id="locked" name="locked" value="1" checked>
      </p>

      <% banned_users, users_to_ban = @script.users.partition(&:banned) %>
      <% if users_to_ban.any? %>
        <p>
          <label for="banned">Ban <%= users_to_ban.map { |u| link_to(u.name, u) }.to_sentence.html_safe %>?</label> <input type="checkbox" id="banned" name="banned" value="1">
        </p>
      <% end %>
      <% if banned_users.any? %>
        <p>(<%= banned_users.map { |u| link_to(u.name, u) }.to_sentence.html_safe %> already banned.)</p>
      <% end %>

      <% @script.users.each do |user| %>
        <% other_scripts = Script.joins(:authors).where(authors: { user_id: user.id }).where(locked: false).where.not(id: @script.id).count unless @script.deleted? %>
        <p><%= user.name %> has <%=link_to("#{other_scripts} other non-locked scripts", user)%>.</p>
      <% end %>
    <% end %>
    <input type="submit" value="Delete">
  <% end %>

  <% if !moderator_view && !@script.locked %>
    <%= render partial: 'permanently_delete', locals: {script: @script} %>
  <% end %>

<% end %>

<% if moderator_view && !@script.permanent_deletion_request_date.nil? %>

  <h3>Permanent deletion</h3>

  <p>The <%= 'author'.pluralize(@script.users.count) %> requested this script be permanently deleted at <%=@script.permanent_deletion_request_date%>. Verify that this script does not contain malware, as permanently deleting would not allow us to blank it out for those who already installed it.</p>

  <%=form_tag(action: 'do_permanent_deletion') do %>
    <p>
      <input type="submit" value="Permanently delete script">
    </p>
  <% end %>

  <p>or...</p>

  <%=form_tag(action: 'reject_permanent_deletion') do %>
    <p>
      <label for="reject_permanent_deletion_reason">Why are you rejecting the request to permanently delete?</label><br>
      <textarea id="reject_permanent_deletion_reason" name="reason" rows="5" cols="100" maxlength="500" required></textarea>
      <input type="submit" value="Reject permanent deletion request">
    </p>
  <% end %>

<% end %>

app/views/scripts/derivatives.html.erb
<%- title t('scripts.derivatives_title', :script_name => @script.name) %>
<%- description 'Potential derivatives of ' + @script.name %>

<p><%=t('scripts.derivatives_intro')%></p>

<h3>Exact copies</h3>

<% identical_svs = @script.script_versions_with_identical_code.group_by(&:script_id).values %>

<% if identical_svs.any? %>
  <p>The following scripts have the exact same code as yours:</p>
  <ul>
    <% identical_svs.each do |svs| %>
      <li>
        <% script = svs.first.script %>
        <%= link_to script.name(request_locale), script_path(script) %> by <%= script.users.map { |u| link_to u.name, user_path(u) }.to_sentence.html_safe %> - versions: <%= svs.map(&:version).uniq.join(', ') %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no other scripts on <%= site_name %> that have the exact same code as this script.</p>
<% end %>


<h3>Similar scripts</h3>

<% check_date = @script.script_similarities.minimum(:checked_at) %>
<% enqueued = ScriptDuplicateCheckerJob.currently_queued_script_ids.include?(@script.id) %>

<p>
  We periodically check the latest version of all other scripts to find the ones most similar to yours. We also check
  whenever you post an update to your script and upon your request.
</p>

<% if check_date %>
  <p>Scores range from 0.000 (completely different) to 1.000 (identical).</p>
  <ul>
    <% @similarities.each do |other_script, score| %>
      <li>
        <%= number_with_precision(score, precision: 3) %>
        <%= link_to '[Diff]', admin_script_path(@script, compare: script_path(other_script), anchor: 'script-comparison') %>:
        <%= link_to(other_script.name(request_locale), other_script) %>
      </li>
    <% end %>
  </ul>
<% end %>

<p>
  <% if enqueued %>
    <% if check_date %>
      We last checked for scripts similar to yours on <%= markup_date(check_date) %>. We will check again shortly.
    <% else %>
      We will check for scripts similar to yours shortly.
    <% end %>
  <% elsif check_date %>
    We last checked for scripts similar to yours on <%= markup_date(check_date) %>.
  <% else %>
    We have not yet checked for scripts similar to yours.
  <% end %>

  <% if !enqueued %>
    <% if check_date.nil? %>
      <%= button_to 'Check now', request_duplicate_check_script_path(@script), method: :POST %>
    <% elsif check_date < 1.day.ago %>
      <%= button_to 'Recheck now', request_duplicate_check_script_path(@script), method: :POST %>
    <% end %>
  <% end %>
</p>

<p>You can also enter some search terms for a live similarity check. The search begins with the most popular scripts matching your query, not the most similar.</p>

<%= form_with(url: similar_search_script_path(@script, format: :json), method: :GET, local: false, html: { id: 'similar-search-form' }) do |f| %>
  <%= f.search_field :terms, required: true %>
  <%= f.submit 'Search' %>
<% end %>

<ul id="similar-search-results">
  <li id="similar-search-more">
    <%= form_with(url: similar_search_script_path(@script, format: :json), method: :GET, local: false, html: { id: 'similar-search-form', data: { 'current-script' => @script.id } }) do |f| %>
      <%= f.hidden_field :terms %>
      <%= f.hidden_field :page %>
      <%= f.submit 'More Results' %>
    <% end %>
  </li>
  <li id="similar-search-none">There are no results matching your query.</li>
</ul>

app/views/scripts/libraries.html.erb
<%- title t('scripts.libraries_title') %>
<%- description 'List of user-submitted libraries available on Greasy Fork' %>

<div class="sidebarred">
  <div class="sidebarred-main-content">
    <div class="open-sidebar sidebar-collapsed">
      ☰
    </div>

    <h2><%=t('scripts.libraries_title')%></h2>

    <p><%=it('scripts.libraries_description_html', policy_link: help_code_rules_path(anchor: 'require'), site_name: site_name)%></p>

    <% if @scripts.empty? %>
      <p><%=t('scripts.listing_no_scripts')%></p>
    <% else %>
      <ol id="browse-script-list" class="script-list">
        <%= render partial: 'script', collection: @scripts, cached: params[:locale_override].nil? ? ->(script) { ['libraries', script, I18n.locale] } : false %>
      </ol>
    <% end %>

    <% if !defined?(@paginate) or @paginate %>
      <%= will_paginate @scripts %>
    <% end %>

    <p><%=t('scripts.write_your_own_html', post_a_script_link: link_to(t('scripts.post_a_script_link_text'), new_script_version_path), learn_to_write_scripts_link: link_to(t('scripts.learn_to_write_scripts_link_text'), help_writing_user_scripts_path)) %></p>
  </div>

  <div class="sidebar collapsed">
    <div class="close-sidebar">
      <div class="sidebar-title"><%= t('common.listing_options_title') %></div>
      <div>☰</div>
    </div>
    <%= render partial: 'list_options', locals: {scripts: @scripts, include_script_sets: false, include_search: true, sort_options: ['created', 'updated', 'name']}%>
  </div>
</div>