config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'sso', to: 'home#sso'

  authenticate :user, ->(user) { user.administrator? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope '(:locale)', locale: /ar|bg|cs|da|de|el|en|es|fi|fr|fr\-CA|he|hu|id|it|ja|ko|nb|nl|eo|pl|pt\-BR|ro|ru|sk|sr|sv|th|tr|uk|vi|zh\-CN|zh\-TW/ do
    get '/users', to: 'users#index', as: 'users'
    get '/users/webhook-info', to: 'users#webhook_info', as: 'user_webhook_info'
    post 'users/webhook-info', to: 'users#webhook_info'
    get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
    delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
    put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
    put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
    put '/users/update_password' => 'users#update_password', :as => 'user_update_password'
    get '/users/delete_info' => 'users#delete_info', :as => 'user_delete_info'
    post '/users/delete_start' => 'users#delete_start', :as => 'user_delete_start'
    get '/users/delete_confirm' => 'users#delete_confirm', :as => 'user_delete_confirm'
    post '/users/delete_complete' => 'users#delete_complete', :as => 'user_delete_complete'
    post '/dismiss_announcement/:key' => 'users#dismiss_announcement', as: 'dismiss_announcement'

    # disable destroying users
    devise_for :users, skip: :registrations, controllers: { sessions: 'sessions' }
    devise_scope :user do
      resource :registration,
               only: [:new, :create, :edit, :update],
               path: 'users',
               path_names: { new: 'sign_up' },
               controller: :registrations,
               as: :user_registration do
        get :cancel
      end
    end
    devise_scope :user do
      # a GET path for logging out for use with the forum
      get '/users/sign_out' => 'sessions#destroy'
      get '/auth/:provider/callback', to: 'sessions#omniauth_callback', as: 'omniauth_callback'
      # BrowserID POSTs
      post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
      get '/auth/failure', to: 'sessions#omniauth_failure'
      get '/auth/failure2', to: 'sessions#omniauth_failure'
      post '/users/send_confirmation_email' => 'users#send_confirmation_email'
    end

    root to: 'home#index'

    get 'scripts/sync_additional_info_form', to: 'scripts#sync_additional_info_form', as: 'script_sync_additional_info_form'
    resources :scripts, only: [:index, :show] do
      member do
        # Deprecated after https://github.com/JasonBarnabe/greasyfork/issues/76
        get 'code.meta.js', to: 'scripts#meta_js', locale: nil
        get 'code.user.js', to: 'scripts#user_js', locale: nil

        match 'code/:name.user.js', to: 'scripts#user_js', as: 'user_js', locale: nil, via: [:get, :options]
        match 'code/:name.user.css', to: 'scripts#user_css', as: 'user_css', locale: nil, via: [:get, :options]
        match 'code/:name.js', to: 'scripts#user_js', as: 'library_js', locale: nil, via: [:get, :options]
        match 'code/:name.meta.js', to: 'scripts#meta_js', as: 'meta_js', locale: nil, via: [:get, :options]
        match 'code/:name.meta.css', to: 'scripts#meta_css', as: 'meta_css', locale: nil, via: [:get, :options]

        get 'admin'
        get 'code(.:format)', to: 'scripts#show_code', as: 'show_code', constraints: { format: /.*/ }
        get 'derivatives'
        get 'similar-search', to: 'scripts#similar_search', as: 'similar_search'
        get 'diff', constraints: ->(req) { !req.params[:v1].blank? && !req.params[:v2].blank? }
        get 'feedback'
        get 'report'
        get 'stats'

        post 'install-ping', locale: nil

        get 'mark'
        post 'mark', to: 'scripts#do_mark', as: 'do_mark'

        get 'delete'
        post 'delete', to: 'scripts#do_delete', as: 'do_delete'
        post 'undelete', to: 'scripts#do_undelete', as: 'do_undelete'
        post 'request_permanent_deletion'
        post 'unrequest_permanent_deletion'
        post 'do_permanent_deletion', to: 'scripts#do_permanent_deletion', as: 'do_permanent_deletion'
        post 'reject_permanent_deletion', to: 'scripts#reject_permanent_deletion', as: 'reject_permanent_deletion'
        patch 'approve'

        patch 'sync_update'
        patch 'update_promoted'
        patch 'update_locale'
        post 'invite'
        get 'accept_invitation'
        post 'remove_author'
        post 'request_duplicate_check'
      end

      collection do
        get 'by-site(.:format)', action: 'by_site', as: 'site_list'
        # :site can contain a dot, make sure site doesn't eat format or vice versa
        get 'by-site/:site(.:format)', action: 'index', as: 'by_site', constraints: { site: /.*?/, format: /|html|atom|json|jsonp/ }
        get 'reported(.:format)', action: 'reported', as: 'reported'
        get 'reported_not_adult(.:format)', action: 'reported_not_adult', as: 'reported_not_adult'
        get 'libraries(.:format)', action: 'libraries', as: 'libraries'
        get 'search(.:format)', action: 'search', as: 'search'
        get 'minified(.:format)', action: 'minified', as: 'minified'
        get 'code-search(.:format)', action: 'code_search', as: 'code_search'
      end

      resources :script_versions, only: [:create, :new, :index], path: 'versions' do
        get 'delete(.:format)', to: 'script_versions#delete', as: 'delete'
        post 'delete(.:format)', to: 'script_versions#do_delete', as: 'do_delete'
      end

      resources :script_reports, path: 'reports', only: [:new, :create, :show, :index] do
        member do
          patch :rebut
          patch :resolve_delete
          patch :dismiss
        end
      end
    end
    resources :script_versions, only: [:create, :new]
    get 'script_versions/additional_info_form', to: 'script_versions#additional_info_form', as: 'script_version_additional_info_form'
    get 'script_versions/confirm_new_author', to: 'script_versions#confirm_new_author', as: 'script_version_confirm_new_author'
    resources :users, only: :show do
      post 'webhook'
      resources :script_sets, only: [:create, :new, :edit, :update, :destroy], path: 'sets'
      get 'ban', to: 'users#ban', as: 'ban'
      post 'ban', to: 'users#do_ban', as: 'do_ban'
    end
    post 'script_sets/add_to_set', to: 'script_sets#add_to_set', as: 'add_to_script_set'

    get 'import', to: 'import#index', as: 'import_start'
    get 'import/userscriptsorg', to: 'import#userscriptsorg', as: 'import_userscriptsorg'
    post 'import/verify', to: 'import#verify', as: 'import_verify'
    post 'import/add', to: 'import#add', as: 'import_add'
    get 'import/url', to: 'import#url', as: 'import_url'

    get 'help', to: 'help#index', as: 'help'
    get 'help/allowed-markup', to: 'help#allowed_markup', as: 'help_allowed_markup'
    get 'help/code-rules', to: 'help#code_rules', as: 'help_code_rules'
    get 'help/contact', to: 'help#contact', as: 'help_contact'
    get 'help/credits', to: 'help#credits', as: 'help_credits'
    get 'help/external-scripts', to: 'help#external_scripts', as: 'help_external_scripts'
    get 'help/installing-user-scripts', to: 'help#installing_user_scripts', as: 'help_installing_user_scripts'
    get 'help/installing-user-styles', to: 'help#installing_user_styles', as: 'help_installing_user_styles'
    get 'help/writing-user-scripts', to: 'help#writing_user_scripts', as: 'help_writing_user_scripts'
    get 'help/rewriting', to: 'help#rewriting', as: 'help_rewriting'
    get 'help/meta-keys', to: 'help#meta_keys', as: 'help_meta_keys'
    get 'help/privacy', to: 'help#privacy', as: 'help_privacy'
    get 'help/user-js-conversions', to: 'help#user_js_conversions', as: 'help_user_js_conversions'

    post 'preview-markup', to: 'home#preview_markup', as: 'preview_markup'
    get 'search', to: 'home#search'

    resources :moderator_actions, only: [:index]

    get 'opensearch.xml', to: 'opensearch#description', as: 'opensearch_description'

    resources :reports, only: [:new, :create, :index] do
      member do
        post :dismiss
        post :uphold
      end
    end

    namespace :admin do
      get '/' => 'home#index'
      resources :ads, only: [] do
        member do
          patch :approve
          patch :reject
        end
        collection do
          get :pending
        end
      end
      resource :analytics_stats, only: [:show, :update]
      resources :blocked_script_codes, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :blocked_script_texts, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :blocked_script_urls, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :redirect_service_domains, only: [:index, :new, :create, :edit, :update, :destroy]
      resources :script_similarities, only: :index
      resources :spammy_email_domains, only: [:index, :new, :create, :edit, :update, :destroy]
    end

    match '*path', to: 'home#routing_error', via: [:get, :post]
  end

  match '*path', to: 'home#routing_error', via: [:get, :post]
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < BaseController
    def index; end
  end
end

app/controllers/home_controller.rb
require 'js_connect'
require 'digest/sha1'

class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:sso, :routing_error]

  def index
    @ad_method = choose_ad_method
    @show_additional_ad = eligible_for_ads?
  end

  def preview_markup
    if params[:url] == 'true'
      begin
        text = ScriptImporter::BaseScriptImporter.download(params[:text])
        absolute_text = ScriptImporter::BaseScriptImporter.absolutize_references(text, params[:text])
        text = absolute_text unless absolute_text.nil?
      rescue ArgumentError => e
        @text = e
        render 'home/error'
        return
      end
    else
      text = params[:text]
    end
    render html: view_context.format_user_text(text, params[:markup])
  end

  def sso
    client_id = Greasyfork::Application.config.vanilla_jsconnect_clientid
    secret = Greasyfork::Application.config.vanilla_jsconnect_secret
    user = {}

    if user_signed_in?
      user['uniqueid'] = current_user.id.to_s
      user['name'] = current_user.name
      user['email'] = current_user.email
      user['photourl'] = ''
    end

    secure = true # this should be true unless you are testing.
    json = JsConnect.js_connect_string(user, params, client_id, secret, secure, Digest::SHA1)

    render js: json
  end

  def search; end
end

app/views/home/error.html.erb
<p><%=@text%></p>

app/views/home/index.html.erb
<%- title t(sleazy? ? 'home.sleazy_title' : 'home.title', site_name: site_name) %>
<%- description "#{site_name} is a free site providing user scripts to improve your web browsing experience." %>

<h2><%=t(sleazy? ? 'home.sleazy_welcome' : 'home.welcome', site_name: site_name)%></h2>

<div id="home-script-nav">
	<%= form_tag(scripts_path, class: 'home-search', method: :get) do %>
		<input type="search" name="q" placeholder="<%=t('home.search_placeholder')%>">
		<input type="submit" value="🔎" class="search-submit" >
	<% end %>
	<div id="home-top-sites">
		<%=t('home.scripts_for_label')%>
		<% ScriptsController.get_top_by_sites(script_subset).map(&:first).compact.first(5).each do |site| %>
			<%= link_to(site, by_site_scripts_path(site: site)) %>
		<% end %>
		<%= link_to t('scripts.listing_filter_by_site_more_sites'), site_list_scripts_path %>
	</div>
</div>

<% if @show_additional_ad %>
  <div id="codefund"><!-- fallback content --></div>
  <script src="https://app.codefund.io/properties/550/funder.js" async="async"></script>
<% end %>

<%= render partial: 'help/installing' %>

app/views/home/routing_error.html.erb
<%- title t('common.not_found_title') %>

<p><%=t('common.not_found_text')%></p>

<p><%=link_to(t('common.not_found_link_home'), root_path)%></p>

app/views/home/search.html.erb
<%= form_tag(scripts_path, id: 'script-search', method: :get) do %>
	<h3><%=t('search.script_search.title')%></h3>
	<p><%=it('search.script_search.description', sphinx_link: 'http://sphinxsearch.com/docs/current/extended-syntax.html')%></p>
	<input type="search" name="q"><input class="search-submit" type="submit" value="🔎">
<% end %>

<%= form_tag(libraries_scripts_path, id: 'library-search', method: :get) do %>
	<h3><%=t('search.library_search.title')%></h3>
	<p><%=it('search.library_search.description', sphinx_link: 'http://sphinxsearch.com/docs/current/extended-syntax.html')%></p>
	<input type="search" name="q"><input class="search-submit" type="submit" value="🔎">
<% end %>

<%= form_tag(code_search_scripts_path, id: 'code-search', method: :get) do %>
	<h3><%=t('search.code_search.title')%></h3>
	<p><%=t('search.code_search.description')%></p>
	<input type="search" name="c"><input class="search-submit" type="submit" value="🔎">
<% end %>

<form action="<%=forum_path%>search" id="forum-search">
	<h3><%=t('search.forum_search.title')%></h3>
	<p><%=it('search.forum_search.description', fulltext_link: 'http://dev.mysql.com/doc/refman/5.7/en/fulltext-natural-language.html')%></p>
	<input type="search" name="Search"><input class="search-submit" type="submit" value="🔎">
</form>

<%= form_tag(users_path, id: 'user-search', method: :get) do %>
	<h3><%=t('search.user_search.title')%></h3>
	<p><%=t('search.user_search.description')%></p>
	<input type="search" name="q"><input class="search-submit" type="submit" value="🔎">
<% end %>